### ISSUE TITLE
Create a webpack plugin to expose the duplication across common chunks

### ISSUE THREAD

**Issue by vigneshshanmugam** [vigneshshanmugam/js-cpa#6]
Generate common chunks Info - https://twitter.com/TheLarkInn/status/884182362917142531

**Comment by pksjce** [comment]
Hey something like this?
https://github.com/kalcifer/BundleDedupePlugin
You'll have to look at the code, I'm not sure which hook in `webpack` to plug into. Would love to know what you had in mind.

**Comment by vigneshshanmugam** [comment]
Cool. I was about to create it anyways :) 

yeah the idea right now is to find the common code patterns across commonchunks and output them across modules. Since webpack is aware of the module dependencies it would be easy to do it really well. 

Boopathi and myself are working currently on handling boundaries across multiple files which will help with common chunks. After this there is one more problem to solve with the AST since webpack uses acron and this project only works with babylon. 

I added you as collaborator to this project 😄  Thanks for your contributions once again, Feel free to shoot your ideas :)

**Comment by pksjce** [comment]
So, my understanding here is - You will look for similarities across chunks, then go back in the sourcemap, identify the modules and then group these modules according to the similarities. Then this output can be fed to ui or cli. Will you be looking for common patterns after commonchunk is formed or before forming it?
Also, is it at all in the realm to actually change the structure of the commonchunk to dedupe for these common patterns?

**Comment by vigneshshanmugam** [comment]
The original idea i had in mind was this

1. Find common code patterns/functions to show them across the common chunks that are created using the webpack plugin.

2. Provide hints to webpack core and improve the common chunks plugin itself to account for duplicates and dedupe the function/modules effectively. 

But the first step is to make this project work across multiple files and provide a sane API. This is already happening in patch-1 branch.

**Comment by pksjce** [comment]
I like the idea of somehow adding this to commonchunksplugin. I can look into if it's possible and how. Will get back to this after you guys are done merging that branch :)

**Comment by vigneshshanmugam** [comment]
Hey,

I played around a bit with this idea and pushed a plugin to report the duplicates. It covers only the first part though https://github.com/vigneshshanmugam/bundle-duplicates-plugin

The second part of providing the hints to common chunks and trying to remove those would need some research in to the webpack core. We can also use your plugin as a playground to play with it.
